---
title: "Florence Ghestem"
---

PhD Student | Biostatistician | R & Python

## About Me

I'm a PhD student in **Biostatistics and Genetic Epidemiology** at [CESP](https://cesp.inserm.fr/) (Université Paris-Saclay, UVSQ, Inserm), Villejuif, in the **HiDiBiostat** team. My PhD is funded through [M4DI](https://m4di.univ-amu.fr/), an interdisciplinary consortium developing methodological frameworks for multimodal biomedical data integration (ANR PEPR Santé Numérique).

My research focuses on developing graph-based machine learning methods to extract genotype-phenotype associations from heterogeneous, multi-scale cohort data (10,000 participants). Integrating clinical, pharmacological, and genomic data using network representations and deep learning approaches.

I am supervised by [Anne-Louise Leutenegger](https://cvscience.aviesan.fr/cv/719/anne-louise-leutenegger) (CESP/NeuroDiderot, INSERM), [Anaïs Baudot](https://www.marseille-medical-genetics.org/a-baudot/) (CNRS/MMG, Aix-Marseille Université), and [Anne-Sophie Jannot](https://heka.gitlabpages.inria.fr/team/members/jannot.html) (BNDMR, HeKA).

Before my PhD, I worked as a biostatistics consultant, leading statistical analyses and cohort project management for industry clients in the cosmetics sector.

When I'm not working, I love hiking and experimenting with creative projects.

## Research Interests

- **Graph Neural Networks & Representation Learning**
- **Knowledge Graphs for Biomedical Data**
- **Statistical Genetics & Genotype-Phenotype Associations**
- **Multi-Modal Data Integration**

## Contact

✉️ [florence.ghestem@inserm.fr](mailto:florence.ghestem@inserm.fr)  
🔗 [ORCID 0009-0000-0699-7751](https://orcid.org/0009-0000-0699-7751)  
💻 [GitHub](https://github.com/FlorenceGhestem)
